[[test.genesis]]
address = "LyfeblocPooL111111111111111111111111111111"
program = "programs/lyfebloc_pool_solana.so"

[[test.genesis]]
address = "LyfeblocFactory111111111111111111111111111"
program = "programs/lyfebloc_factory_solana.so"

[[test.genesis]]
address = "LyfeblocRouter1111111111111111111111111111"
program = "programs/lyfebloc_router_solana.so"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
